### ISSUE TITLE
Using multi line statements fails

### ISSUE THREAD

**Issue by AbdealiLoKo** [BerniWittmann/background-server-action#137]
I was trying to do:
```yml
            - name: Run tests
              uses: BerniWittmann/background-server-action@v1
              with:
                  command: |
                      NODE_OPTIONS="--max-old-space-size=4096" \
                        ng test \
                        --no-watch --no-progress --source-map=false \
                        --browsers=ChromeHeadlessCI
```
But that fails as it looks like this is considered to be 4 different commands.
I saw this in the github action logs:
```sh
/usr/bin/bash -c NODE_OPTIONS="--max-old-space-size=4096" \
/usr/bin/bash -c ng test \
/usr/bin/bash -c --no-watch --no-progress --source-map=false \
/usr/bin/bash -c --browsers=ChromeHeadlessCI
```
