### ISSUE TITLE
Unable to resolve action BerniWittmann/background-server-action@latest

### ISSUE THREAD

**Issue by basz** [BerniWittmann/background-server-action#53]
Hi,

why would i get this error?

Error: Unable to resolve action `BerniWittmann/background-server-action@latest`, unable to find version `latest`

```
name: Testing

on:
  push:
    branches: [main]

jobs:
  run-tests:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install dependencies
        run: yarn --frozen-lockfile --silent

      - name: Run integration tests
        uses: BerniWittmann/background-server-action@1.0.4
        with:
          command: yarn test
          start: yarn start
          wait-on: 'http://localhost:4201'
          wait-on-timeout: 120
```

edit: 

I tried both 'latest' and a 'specific' version. Both results in "Unable to resolve action"
