### ISSUE TITLE
seemingly broken

### ISSUE THREAD

**Issue by justin-barca-at-camis** [BerniWittmann/background-server-action#68]
Does not run tasks successfully after testing locally with error message in CI:

```
/home/runner/work/_actions/BerniWittmann/background-server-action/v1.0.4/webpack:/background-server-action/index.js:177
  .then(startServersMaybe)
^
TypeError: Cannot read property 'then' of undefined
    at Object.2932 (/home/runner/work/_actions/BerniWittmann/background-server-action/v1.0.4/webpack:/background-server-action/index.js:177:1)
    at __nccwpck_require__ (/home/runner/work/_actions/BerniWittmann/background-server-action/v1.0.4/webpack:/background-server-action/webpack/bootstrap:20:1)
    at /home/runner/work/_actions/BerniWittmann/background-server-action/v1.0.4/webpack:/background-server-action/webpack/startup:4:1
    at Object.<anonymous> (/home/runner/work/_actions/BerniWittmann/background-server-action/v1.0.4/dist/index.js:12008:12)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
```

This is the config:

```
- name: Nightwatch E2E via Percy
    env:
      PERCY_TOKEN: ${{secrets.PERCY_TOKEN}}
    uses: BerniWittmann/background-server-action@v1.0.4
    with:
      command: yarn percy-e2e
      start: yarn mock-server, yarn start
      # quote the url to be safe against YML parsing surprises
      wait-on: 'https://localhost:3000'
```

and was performed after a checkout as in example.

**Comment by pomSense** [comment]
+1 on this issue

**Comment by AmmonMatthews** [comment]
@justin-barca-at-camis When implementing this the last few days. The way around it was I had to run a build command of my app first. Here is an example that I believe will work with your code. 

```
- name: Nightwatch E2E via Percy
    env:
      PERCY_TOKEN: ${{secrets.PERCY_TOKEN}}
    uses: BerniWittmann/background-server-action@v1.0.4
    with:
      command: yarn percy-e2e
      build: <run your build script here>
      start: yarn mock-server, yarn start
      # quote the url to be safe against YML parsing surprises
      wait-on: 'https://localhost:3000'
      ```
