### ISSUE TITLE
Support for specifying working directory

### ISSUE THREAD

**Issue by pomSense** [BerniWittmann/background-server-action#89]
## Description
As a user, I should be able to specify the working directory similar to GitHub Action's `working-directory` option. This will allow users of yarn workspaces or monorepos to tightly control which directory a server/command should be run

## Proposed solution
Add a working directory option similar to Github working directory:
```yml
    - name: run ci-integration tests
      uses: BerniWittmann/background-server-action@latest
      working-directory: packages/my_package
      with:
        command: yarn jest --testMatch='**/integration-tests/**/*test.ts' --ci --maxWorkers=50%
        start: yarn start
```
